# This is the configuration used to check the rubocop source code.

AllCops:
  Excludes:
    - spec/*.rb

#Customize rules
Metrics/LineLength:
  Max: 95

# Metrics/MethodLength:
#   Max: 15

Style/MutableConstant:
  Enabled: false
