# This is the configuration used to check the rubocop source code.

AllCops:
  Excludes:
    - spec/*.rb

#Customize rules
Metrics/LineLength:
  Max: 95

Metrics/MethodLength:
  Max: 35

Metrics/AbcSize:
  Enabled: false

BlockLength:
  Max: 70

Style/MutableConstant:
  Enabled: false
